### PR TITLE
Add type stubs to datasets

### PR DESCRIPTION
**Pull request by chaichontat**
## Description
Add type stubs to datasets.

## How has this been tested?
Pre-commit and test suites
Note the need to exclude original *.py files from the mypy pre-commit due to pre-commit/mirrors-mypy#33. A solution to maintain type safety would be to add a full mypy/pyright step to the CI workflow.

### CODE REVIEW

**Comment by michalk8** [comment]
Thanks for the PR, @chaichontat . Could you please change the type hints to `Callable[[PathLike, Any], AnnData]` and `Callable[[PathLike, Any], ImageContainer]` using `from squidpy.datasets._utils import PathLike` ? That should match the signature; after that will happily merge.

**Comment by chaichontat** [comment]
> Thanks for the PR, @chaichontat . Could you please change the type hints to `Callable[[PathLike, Any], AnnData]` and `Callable[[PathLike, Any], ImageContainer]` using `from squidpy.datasets._utils import PathLike` ? That should match the signature; after that will happily merge.

Thanks! I didn't look closely enough. More reasons why types are useful.

**Comment by chaichontat** [comment]
Please hold off on merging for now. I think I have a better idea.

**Comment by chaichontat** [comment]
Seems like the lint failure is due to
```
Writing C:\Users\Chaichontat\GitHub\squidpy\docs\build\spellcheck\external_tutorials/tutorial_napari.spelling
writing output... [100%] tutorials
C:\Users\Chaichontat\GitHub\squidpy\docs\source\external_tutorials\tutorial_napari.ipynb:136: WARNING: Spell check: searchable: ["search able", "search-able", "unsearchable", "reachable", "chargeable", "shareable"]: The widgets are searchable, meaning that you can type the initials of e.g. your favorite gene and the menu will automatically scroll to the location automatically. In order to visualize the feature of interest as an additional layer, you can either press .
C:\Users\Chaichontat\GitHub\squidpy\docs\source\external_tutorials\tutorial_napari.ipynb:225: WARNING: Spell check: searchable: ["search able", "search-able", "unsearchable", "reachable", "chargeable", "shareable"]:  are also searchable and can be visualized. For instance, Squidpy stores the results of the image feature extraction step in .
WARNING: Found 2 misspelled words
build finished with problems, 4 warnings.
```
and this dead link.
https://github.com/theislab/squidpy/blob/b6165be6dc32b0d89336e865a76ecc42ddcccc85/docs/source/conf.py#L81

**Comment by giovp** [comment]
That's awesome @chaichontat thanks a lot! We can skip spellcheck and fix them another time! Not sure about the napari docs... Should be good to merge on my side.

**Comment by chaichontat** [comment]
Looks good to me as well. Napari seems to have moved their docs to the main page https://napari.org/.

**Comment by michalk8** [comment]
``napari`` link has been fixed, but https://pepy.tech (for our downloads badge) is not accessible; nothing we can do there right now, so am merging this, thanks @chaichontat !

**Pull request merged**
