### PR TITLE
start release 1.1.0

### PR DESCRIPTION
**Pull request by giovp**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (change that would cause existing functionality to not work as before)
- [ ] New feature (non-breaking change which adds functionality)

### Description

Addresses #366 

### How has this been tested?

...

### Closes

...

### CODE REVIEW

**Comment by giovp** [comment]
your solution with raw worked @michalk8 but did not render on pypi (failed `tox -e readme` failed).
following this: https://github.com/github/markup/issues/163
it seems that the `image..` rst directive is correct in pypi but wrong in git. I would therefore stick to that and nevermind for not aligning in the github readme (where we could even remove the large image in the first place tbh.)
also the image `figure1.png` will be different when we merge dev to master (correct updated version)

**Comment by michalk8** [comment]
> your solution with raw worked @michalk8 but did not render on pypi (failed tox -e readme failed).
following this: github/markup#163

Let's move this to #377 - I was working on this when you opened this draft PR.

**Comment by giovp** [comment]
ok great! I will add these changes there

**Comment by michalk8** [comment]
closed in favor of #377

**Pull request closed without merging**
