### PR TITLE
Remote Zarr Image Container

### PR DESCRIPTION
**Pull request by ilan-gold**
## Description
This PR is somewhat short, but I learned a lot along the way!

This PR basically adds support for a zarr xarray dataset to be stored remotely, on a file server, and then read in by squidpy.

You can test this by doing something like:

1. Starting a http server:
```bash
brew install http-server
http-server -p 8080
```

2. And then:
```python
import squidpy as sq
img = sq.im.ImageContainer('http://127.0.0.1:8080/test_visium.zarr/')
crop = img.crop_corner(1000, 1000, size=1000)
sq.im.segment(img=crop, layer="image", method="watershed", channel_ids=0)
crop.show('segmented_watershed')
```

And you should see the image data flowing out of the server and into squidpy (`http-server` logs requests).

Part of the reason this took me so long is that I had to figure out how to get the data to load lazily (without confirming this, I can only be certain I've just written syntatic sugar for a download method  :smile:).  There were a few things I noticed here:

1.  I needed to add special arguments for lazy-loading.   I think that because dask is used in `squidpy`, I assumed this would be the default.  However without these arguments, the `segment` call prompted the actual computation of the segmentation which was unexpected.  Is this right for lazy-loading in terms of arguments? Too much?  I was a little confused as to `chunks` vs `lazy`.
```python
import squidpy as sq
# This doesn't seem to work without the `chunks` argument, which appears to be undocumented:
# https://squidpy.readthedocs.io/en/latest/classes/squidpy.im.ImageContainer.html
img = sq.im.ImageContainer('http://127.0.0.1:8080/test_visium.zarr/', chunks='auto')
crop = img.crop_corner(1000, 1000, size=1000)
sq.im.segment(img=crop, layer="image", method="watershed", channel_ids=0, chunks='auto', lazy=True)
crop.show('segmented_watershed')
```

2.   It took me a very long time to figure out that tests don't seem to work with python 3.9 on macos: #392 and https://github.com/theislab/squidpy/blob/c9317870fbac631de523596737dc837c8bdb66b5/.github/workflows/test.yml#L42-L54 or at least I couldn't get around a very starnge hdf5 issue that seems to have been documented in #392.  Is this still an issue?  The issue itself is closed but the CI doesn't run the tests on macos for python 3.9 it seems.

3.  Running the following computes the watershed over the whole image and then only shows the crop.  I guess this makes sense to some degree since you ask the computation to be done on the whole image and then only show a crop of it, especially given that `otsu` thresholding requires loading all the data, but it took me a bit to figure this out.  I thought the computation task would transfer to the crop independently.   Maybe some documentation about how lazy-loading in squidpy work?  Perhaps we could do this hand-in-hand with the first point?

```python
import squidpy as sq
img = sq.im.ImageContainer('http://127.0.0.1:8080/test_visium.zarr/', chunks='auto')
sq.im.segment(img=img, layer="image", method="watershed", channel_ids=0, chunks='auto', lazy=True)
crop = img.crop_corner(1000, 1000, size=1000)
crop.show('segmented_watershed')
```

The last thing is OME-NGFF.  I'm not sure what the best way forward is here.  One thing is that the data format is just completely different from `xarray`'s own data format, which seems to have some metadata and structure requirements:  https://xarray.pydata.org/en/stable/generated/xarray.open_dataset.html

Another thing is that OME-NGFF is mutliscale while `squidpy` and `xarray` are not from what I can tell.  So I'm not totally sure what to do about that either.  I'll maybe open an issue for this and continue the discussion there?

## How has this been tested?
I updated the io unit test to include remote datasets

### CODE REVIEW

**Comment by giovp** [comment]
@michalk8 why did you close this? I think it'd be cool to have

**Comment by michalk8** [comment]
> @michalk8 why did you close this? I think it'd be cool to have

Sorry, must've happened automatically when I removed `dev`. @ilan-gold would be great if you could reopen.

**Comment by ilan-gold** [comment]
I cannot reopen.....

**Comment by ilan-gold** [comment]
I can just open a new PR though unless one of you has the option to re-open

**Comment by giovp** [comment]
I also can't reopen 😓 sorry ! better new PR

**Comment by michalk8** [comment]
> I can just open a new PR though unless one of you has the option to re-open

Yeah, sorry for causing confusion, please open a new PR.

**Comment by michalk8** [comment]
@ilan-gold could you please open a new PR?

**Comment by ilan-gold** [comment]
Done @michalk8 but I think there are merge conficts

**Pull request closed without merging**
