### PR TITLE
remove `githup_repo` arg from conf sphinx

### PR DESCRIPTION
**Pull request by giovp**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (change that would cause existing functionality to not work as before)
- [ ] New feature (non-breaking change which adds functionality)

### Description

...

### How has this been tested?

...

### Closes

...

### CODE REVIEW

**Comment by michalk8** [comment]
@giovp I've fixed it so that the links to tutorials/examples/rst are correct.
However, for auto-generated files by sphinx, such as `https://squidpy.readthedocs.io/en/latest/api/squidpy.gr.centrality_scores.html#squidpy.gr.centrality_scores` which are not commited to the repo, it's still broken.
I will fix it later - I remember scVelo has this: https://github.com/theislab/scvelo/blob/master/docs/source/conf.py#L224
and we can have a simplified version (without the line from, line to, since we already use an extension for it).

**Review by michalk8 — APPROVED** [review]

**Comment by giovp** [comment]
> I will fix it later - I remember scVelo has this: https://github.com/theislab/scvelo/blob/master/docs/source/conf.py#L224
and we can have a simplified version (without the line from, line to, since we already use an extension for it).

those are really fine, not pressing. Thanks for addressing this real quick!

Have a related question actually, I know we discussed this already but I noticed the repo is ~50 Mb and a lot comes from the notebooks (~46 Mb are in  `.git` ). This is because the way we set up running and rendering the notebooks right? There is no workaround to save them there and render them on the docs from there? sorry if repeating myself

**Comment by michalk8** [comment]
@giovp this is because we still have that old branch https://github.com/theislab/squidpy/tree/feature_scaling2,
the repo cleaner did its job. I've created my own fork and deleted the branch, then the .git/objects are only 3MB.
@LouisK92 could you please recreate the changes from on branch based-off the current master and delete the old one? That should fix it.

Regarding the repo size of `squidpy_notebooks`, unfortunately, there we commit the generated .ipynb so that they are downloadable/viewable through binder. There are 63MB in the .git/objects, 39MB are in the docs (mostly matplotlib figures).
A workaround would be to upload all generated stuff as artifacts on github (e.g. as a compressed tar), instead of commiting them and then download these when building the main docs (should be fairly easy). Downside is that we'd lose links to binder + unforseen consequences (not sure about rate limits and retention policy).

**Comment by LouisK92** [comment]
deleted the branch (and made a copy of the changes). Is it fixed?

**Comment by michalk8** [comment]
Yes, it's fixed (just have to reclone), thanks a lot.

**Pull request merged**
