### PR TITLE
extend graph build

### PR DESCRIPTION
**Pull request by Koncopd**
https://github.com/theislab/squidpy/issues/325

Replaced `CoordType.VISIUM` with `CoordType.GRID`.
Added `neigh_grid` for grid coordinates. It is `int` now, i think it is the most flexible variant.
Distances are passed for `n_rings=1` also, though it is the same matrix as in connectivities.

### CODE REVIEW

**Comment by giovp** [comment]
@Koncopd I don't think the `neigh_grid=4` is working:
image

I would expect this:
image

reprex

```python
import numpy as np
from anndata import AnnData

rng = np.random.default_rng(42)
coord = rng.integers(
    0,
    12,
    size=(200, 2),
)
coord = np.unique(coord, axis=0)
counts = rng.integers(0, 10, size=(coord.shape[0], 10))
adata = AnnData(counts)
adata.obsm["spatial"] = coord

sq.gr.spatial_neighbors(adata, neigh_grid=4)
# or
sq.gr.spatial_neighbors(adata, radius=1.0)
```

**Comment by giovp** [comment]
hey @Koncopd ,

I've experimenting a bit more and still no success

```python
import numpy as np
from anndata import AnnData

rng = np.random.default_rng(42)
coord = rng.integers(0, 12, size=(200, 2))
coord = np.unique(coord, axis=0)
counts = rng.integers(0, 10, size=(coord.shape[0], 10))
adata = AnnData(counts)
adata.obsm["spatial"] = coord

n_rings, n_neigh, sum_dist = (2, 4, 0)
sq.gr.spatial_neighbors(adata, coord_type="grid", n_rings=n_rings, neigh_grid=n_neigh)
np.diff(adata.obsp["spatial_connectivities"].indptr).max() 
# this one gives 11, it should give 8 (it gives eight with radius = 1)

sc.pl.spatial(
    adata, spot_size=0.2, edges=True, edges_width=2, neighbors_key="spatial_neighbors"
)
```
image


beside the fact that `np.diff` gives the wrong result, see for instance the bottom right point that is not connected to anything (although it should)...
I wonder if this si a bug from nearestneighbor from scikit learn? Not sure
Maybe I'll try to have a look again tomorrow....

**Comment by Koncopd** [comment]
And why should the bottom one be connected to anything actually?

**Comment by giovp** [comment]
> Also radius=1. and n_rings=1 are the same (with max diff of 4). I don't understand why you compare n_rings=2 with radius=1.

with `n_rings=2` it should be 8 max diff, not 11 as it is now. I don't understand where that 11 come from

**Comment by Koncopd** [comment]
Taking `radius=2.` is not the same as `n_rings=2` For example, the bottom one becomes connected with `radius=2.` and stays disconnected with `n_rings=2.` because it how the algorithm works now. We walk through neighbors, neighbors of neighbors and so on. If there are no neighbors it stays isolated. This is rather a question of how we build `n_rings`, i am pretty sure we discussed this.

**Comment by giovp** [comment]
thanks @Koncopd !
weird bug in napari test but ok. Will merge this!

**Review by giovp — APPROVED** [review]

**Pull request merged**
